### ISSUE TITLE
Add ability to create videos in visualizer

### ISSUE THREAD

**Issue by Kraysent** [Kraysent/OMTool#131]
**Problem**: for now visualizer can create only images according to ceratain pattern. 
**Desired functionality**: ability to specify video and its parameters in configuration file
**Approach**:
```yaml
visualizer:
  output_dir: ....
  pic_filename: .....
  video:
    name: "some name.mp4"
    frame_frequency: 5
    ...
  ...
```

Solution lies somewhere in `FuncAnimation` field
