### ISSUE TITLE
Use tasks' output in next tasks inputs

### ISSUE THREAD

**Issue by Kraysent** [Kraysent/OMTool#145]
Proposed feature would divide task parameteres into static and dynamic. Static ones are described in `args` section of the configuration while dynamic ones are in `inputs` section. 

Static parameters do not change once task is described. Dynamic ones take their values based on the output of the previously launched tasks. Minimal example is as follows:

```yaml
tasks:
  - name: PotentialCenterTask
    id: host_potential_center
    actions_before:
      - type: slice
        parts: [[0, 0.6666]]
  - name: PotentialCenterTask
    id: sat_potential_center
    actions_before:
      - type: slice
        parts: [[0.6666, 1]]
  - name: DistanceTask
    inputs:
      start_position: host_potential_center.position
      end_position: sat_potential_center.position
    actions_after:
      - type: logging
        print_last: True
        id: distance_data
```

Here, DistanceTask should have `**kwargs` in its `run` method with names `start_position` and `end_position`. OMTool would read these values from the `PotentialCenterTask`'s output under the key `position`. This key should hold valid value that would be passed into the `run` method.

Several new fields would be added to the task description:
- `id`: textual identificator of the task. Should be unique. If now specified, defaults to `task_{i}`, where `i` is the index number of the task in the configuration file.
- `inputs`: dictionary of keywoard arguments that would be passed into the `run` method. For now all of the values are interpreted as `id.field` paths. In future there might be some mechanism that allows to pass static values there.
