### ISSUE TITLE
Add ability to desribe user's own formula in task description

### ISSUE THREAD

**Issue by Kraysent** [Kraysent/OMTool#43]
Program should have finite set of task types: scatter task, time task and radial distribution task. User should be able to choose one of these and then create description of its task in form similar to the following:
```
- name: ScatterTask
  args:
    x_expr: 'sqrt(x^2 + y^2 + z^2)'
    y_expr: 'y'
    x_unit: !q [1, kpc]
    y_unit: !q [1, kpc]
```

These expressions should be parsed with https://github.com/Kraysent/Physical-Evaluator.

- [x] Scatter task
- [x] Evolution over time task
