### ISSUE TITLE
Move model reading process to a separate microservice

### ISSUE THREAD

**Issue by Kraysent** [Kraysent/OMTool#64]
**Problem**: both integration and analysis tools have very similar modules that read models from disk and then operate on them. This causes duplication of code and creates two maintaining processes that can be merged into one.  

**Possible solution**: create separate microservice in the root of repository that would operate like a blackbox: input is config dictionary like so:
```yaml
input:
  - type: fits
    filename: /home/user/model.fits
  - type: csv
    filename: /home/user/host.csv
```
and the output is a generator of `Snapshot` objects and probably single method to show the number of snapshots or something like that.
