### ISSUE TITLE
Move logging into separate microservice

### ISSUE THREAD

**Issue by Kraysent** [Kraysent/OMTool#65]
**Problem**: logging process is located in the separate module inside of datamodel but it's config is read with clunky and unscalable way. 

**Possible solution**: move logging module into the root of repository as a separate microservice and make it a blackbox. Input of this blackbox is the config dictionary like:
```yaml
logging:
  - handler_type: console
    args:
      format: '[%(levelname)s] %(asctime)s | %(message)s'
      stream: stdout
  - handler_type: file
    args: 
      format: '[%(levelname)s] %(asctime)s | %(message)s'
      filename: !env '{WORKING_DIR}/test_log.txt'
      datefmt: '%H:%M:%S'
```
and the output is a set of functions that give an ability to log anything one might want.
