### ISSUE TITLE
Move visualizer into separate microservice

### ISSUE THREAD

**Issue by Kraysent** [Kraysent/OMTool#66]
**Problem**: analysis config has too much nesting levels in it. 

**Possible solution**: move visualizer code and description of the plots into separate microservice. As with other microservices it should be a black box with configuration as input:
```yaml
matplotlib_visualizer:
  plot_interval: [0, null, 1]
  output_dir: !env '{WORKING_DIR}/analysis'
  title: 'Time: {time:.02f} Myr'
  figsize: [20, 11]
  pic_filename: 'img-{i:03d}.png'
  panels:
    - id: zy_plane
      coords: [0, 0.35, 0.35, 0.6]
      params: 
        xlim: [-45, 45]
        ylim: [-40, 40]
        xlabel: 'z, kpc'
        ylabel: 'y, kpc'
        xticks: [0, 10]
        yticks: [0, 10]
    - ...
```
And output in form of `plot(data, params)`, `set_title(text)` and `save()` functions. 

Then tasks can reference to the plot id in their `display` option.
