### ISSUE TITLE
Move task visualizer parameters into handlers

### ISSUE THREAD

**Issue by Kraysent** [Kraysent/OMTool#72]
Every task should have `handlers` object which is the dictionary:  

```yaml
    handlers:
      visualizer:
        id: potential_dist_plane
        linestyle: None
        color: *host_clr
        label: host
```

then for each handler its `run_handler` function woud run and operate on data.
