### ISSUE TITLE
Untie integration process from the pyfalcon integrator

### ISSUE THREAD

**Issue by Kraysent** [Kraysent/OMTool#89]
Integrator should be specified in confiiguration file. Example:
```yaml
...
integrator: 
  type: pyfalcon
  args:
    timestep: 7
    eps: !q [0.2, kpc]
...
```
